### ISSUE TITLE
"Load More" not work in main report

### ISSUE THREAD

**Issue by liweijian** [screenshotbot/screenshotbot-oss#17]
<img width=800 src="https://user-images.githubusercontent.com/19320783/152670347-6740aeda-e1bd-4713-a462-9acf9e106702.gif">

"Load More" not work in main report, but it works well in "All Pixel Comparison" page as follow:
<img width="800" alt="all_comparison_ok" src="https://user-images.githubusercontent.com/19320783/152670367-2b54318c-a6bc-41e4-81bd-accc7f62abaf.png">

**Comment by tdrhq** [comment]
Hmm, I'm not able to reproduce. Which commit are you on?

**Comment by tdrhq** [comment]
I've added some more UI feedback in https://github.com/screenshotbot/screenshotbot-oss/commit/ae49b0faea8b2c4a509c846ad348194e1fc18d75

(In particular, I wasn't disabling the Load More button while the page was loading. I can't see how this would cause this, but it *might* if the server was overloaded or something).

Once you restart with this commit, and if it still doesn't work, can you send me the full "Console" logs and the network logs?

Thanks!

**Comment by liweijian** [comment]
<img width=600 src="https://user-images.githubusercontent.com/19320783/152686210-a794e2a1-bf30-4da1-9680-26a3100ebf4f.png">

**Comment by liweijian** [comment]
<img width=800 src="https://user-images.githubusercontent.com/19320783/152686311-4040151f-66e6-4125-83ec-1b1d8f883906.png">

<img width=800 src="https://user-images.githubusercontent.com/19320783/152686349-1fbdb875-37fb-44a9-b139-61df62130120.png">

**Comment by liweijian** [comment]
For the commit

```shell
$ git log
commit 47581312685ecba336edfb4e98ed799f053be749 (HEAD -> hide_imags_within_thredhold_in_all_comparison_page)
Merge: 7732c11 7782bde
Author: liweijian 
Date:   Sun Feb 6 22:36:00 2022 +0800

    Merge branch 'main' of https://github.com/screenshotbot/screenshotbot-oss into hide_imags_within_thredhold_in_all_comparison_page

commit 7782bde1d681ab1f72522ee5fc5072b0f1fe835b
Author: Arnold Noronha
Date:   Sun Feb 6 08:46:03 2022 -0500

    Also use the new header on the Added/deleted
    
    Differential Revision: https://phabricator.tdrhq.com/D4781
    
    GitOrigin-RevId: ca3340f84f6a11bcab8a0b766326008f48a04c43
```

**Comment by tdrhq** [comment]
I'm going to make an experimental change, and let me know if that fixes things for you. The line in question is this: https://github.com/screenshotbot/screenshotbot-oss/blob/main/src/screenshotbot/js/default.js#L280

It uses jquery live events, perhaps that isn't working correctly on your browser. Let me make it use regular events.

Give me a few minutes to make the change.

**Comment by tdrhq** [comment]
Although... that doesn't make sense. You said it works find on the all comparisons page, that's the same logic. Hmm..

**Comment by liweijian** [comment]
> Although... that doesn't make sense. You said it works find on the all comparisons page, that's the same logic. Hmm..

It's weird :(

**Comment by tdrhq** [comment]
Does the button work for you the first time after loading the page? Or does it not work at all? (The logic might work a bit differently the second time you click it).

Can you also make sure you press Ctrl+F5 to force reload any cached javascript?

**Comment by liweijian** [comment]
> Can you also make sure you press Ctrl+F5 to force reload any cached javascript?

I did press Ctrl+F5 many times, and there're lots of 304 return

> Does the button work for you the first time after loading the page? Or does it not work at all?

It doesn't work at all in the main report.

**Comment by liweijian** [comment]
I'll take a look at it. `console.log("Fetching next page");` shows in the "All Pixel" page:

<img width=600 src="https://user-images.githubusercontent.com/19320783/152687784-bf8ad4e0-51e4-45b5-9a99-bc01b916cb85.png">

**Comment by liweijian** [comment]
Is it possible the icons failed to load which trigger this error?

<img width=600 src="https://user-images.githubusercontent.com/19320783/152687897-775f97d1-f717-4e92-9c79-d2eeff1674e1.png">

**Comment by tdrhq** [comment]
> Is it possible the icons failed to load which trigger this error?

Seems *very* unlikely. But that does tell me why your icons are not showing (the play_circle/book/flag in your left side navbar)

**Comment by liweijian** [comment]
![image](https://user-images.githubusercontent.com/19320783/152688101-7a951f73-f1b5-40ed-988b-7ab5c9ef7324.png)


On the main report, that's all. The `Setting up image comparison on: jQuery.fn.init` missing

**Comment by liweijian** [comment]
> > Is it possible the icons failed to load which trigger this error?
> 
> Seems _very_ unlikely. But that does tell me why your icons are not showing (the play_circle/book/flag in your left side navbar)
> 
> Can you tell me why this is failing to load? Is it being blocked as a corporate policy, or something to do with how Google Fonts works in China?

It sounds a lot like we can't access some Google domains here.

![image](https://user-images.githubusercontent.com/19320783/152688208-3695752c-7efe-42a8-96f4-508437e37040.png)

**Comment by tdrhq** [comment]
> It sounds a lot like we can't access some Google domains here.

Hmm, I'll update the code to use a local image instead of google fonts. (Internal tracking task: t154)

**Comment by tdrhq** [comment]
I'm able to reproduce on the open source version. Let me dig through this and get back to you real quick

**Comment by tdrhq** [comment]
Ah: in particular this happens when you manually compare two runs, not when you load a report. The reason for that being that manually comparing two runs is asynchronous. I'll fix this.

**Comment by tdrhq** [comment]
I've pushed a fix: https://github.com/screenshotbot/screenshotbot-oss/commit/0f5e5472099902c4a09388a8ca53165b936e57ca
Could you let me know if it works for you now?

**Comment by tdrhq** [comment]
The icons should also be fixed now

**Comment by liweijian** [comment]
> The icons should also be fixed now

Confirmed

> I've pushed a fix: https://github.com/screenshotbot/screenshotbot-oss/commit/0f5e5472099902c4a09388a8ca53165b936e57ca
> Could you let me know if it works for you now?

Confirmed

Awesome!
