### ISSUE TITLE
Broken link in Web console

### ISSUE THREAD

**Issue by SamCosta1** [screenshotbot/screenshotbot-oss#20]
Minor issue, but there's a broken link in the web console.

## Report created with following:

```
~/screenshotbot/recorder \
     --directory "./reports/ios_screenshots" \
     --channel "screenshots-test" \
     --main-branch "master" \
     --api-key "<my api key>" \
     --api-secret "<my api secret>" \
     --repo-url "https://bitbucket.org/myorg/org-project.git"
```

## Tapping the following link:
![Screenshot 2022-06-13 at 14 59 36](https://user-images.githubusercontent.com/16070190/173370762-5cf80172-32a9-4ced-b7db-6176081ab3c7.png)

## Expected result:

Navigated to: https://bitbucket.org/myorg/org-project.git/commits/e4418358742b8f7c73e980bf631f3222c7e8fcfb

## Actual Result

Navigated to: https://bitbucket.org/https:/bitbucket.org/myorg/org-project.git/commit/e4418358742b8f7c73e980bf631f3222c7e8fcfb

It looks as though the base url is getting repeated, and also the path param should be "commit**s**" rather than "commit".

(Though I might well have misconfigured something :) )

**Comment by tdrhq** [comment]
Fixed!

**Comment by SamCosta1** [comment]
Perfect thank you!
