### ISSUE TITLE
How to promote test runs?

### ISSUE THREAD

**Issue by SamCosta1** [screenshotbot/screenshotbot-oss#21]
More of a question than an issue.

But how can I promote a run via the cli? I'm currently seeing a list of unpromoted runs in my dashboard but can't see any way to promote one

![Screenshot 2022-06-13 at 17 49 33](https://user-images.githubusercontent.com/16070190/173404518-4cd44a27-da4f-405f-baf9-d3b858d777f4.png)

However there are some errors in the promotion log so possibly this is to do with the fact I'm using bitbucket?

```
  --BEGIN-LOGS--
ERROR: No github installation id avaialble
INFO: Repo is of type: SCREENSHOTBOT/PRO/BITBUCKET/PLUGIN:BITBUCKET-REPO
ERROR: No github installation id avaialble
INFO: Repo is of type: SCREENSHOTBOT/PRO/BITBUCKET/PLUGIN:BITBUCKET-REPO
ERROR: No github installation id avaialble
INFO: Repo is of type: SCREENSHOTBOT/PRO/BITBUCKET/PLUGIN:BITBUCKET-REPO
ERROR: No github installation id avaialble
INFO: Repo is of type: SCREENSHOTBOT/PRO/BITBUCKET/PLUGIN:BITBUCKET-REPO

  --END-LOGS--
```

**Comment by tdrhq** [comment]
Let me take a look, it does look like something crashed in the Bitbucket logic

**Comment by SamCosta1** [comment]
I think the issue was the way I was running the test runs, I was doing them locally and in a strange order. 

I cleaned a few things up and this is now working! Thank you!
