### ISSUE TITLE
Feature Request: Ability to manually specify commit hash when creating a run

### ISSUE THREAD

**Issue by SamCosta1** [screenshotbot/screenshotbot-oss#22]
## Context:

As part of our CI pipeline for Pull Requests we merge our destination branch into our feature branch in order to run code coverage and tests.

This means that the commit hash when we create the run using

```
~/screenshotbot/recorder \
     --directory ......... etc
```

does not actually match the commit hash of the Pull Request. 

## Actual feature request

Ability to manually specify the commit hash to the script so that we can do something like:

```
~/screenshotbot/recorder \
     --directory "./reports/ios_screenshots" \
     --commit_hash $COMMIT_HASH_FROM_CI_ENV
   ... etc
```

Which would override the one being pulled directly from source control.

This is of course not a gamechanger, we can easily deal with it locally, but it would optimise the workflow

**Comment by tdrhq** [comment]
This makes sense, let me add it. There are a few details I need to get right, but I think I should have it ready at least in a few hours if not sooner.

**Comment by SamCosta1** [comment]
No rush! Thank you so much!
