### ISSUE TITLE
https://screenshotbot.io/recorder is down (404)

### ISSUE THREAD

**Issue by wezley98** [screenshotbot/screenshotbot-oss#28]
The curl command for https://screenshotbot.io/recorder is currently not working as the endpoint is returning a 404.

**Comment by tdrhq** [comment]
@wezley98 The url is `https://screenshotbot.io/recorder.sh` (note the `.sh` at the end).

Could you tell me where you got the URL you used? This is the second time in the last few days somebody referenced the wrong URL, so I'm wondering if I've mentioned it incorrectly in some doc.

**Comment by tdrhq** [comment]
I added a informative 404 page just for /recorder, just so telling the user what the actual page is (since it might be different based on Linux/Darwin or Windows, I didn't want to outright redirect): https://github.com/screenshotbot/screenshotbot-oss/commit/5e7c83639e68f4a56192f751bedc18c0ddc3faab

**Comment by wezley98** [comment]
@tdrhq Thank you. Do the docs need updating as well?

from
` curl https://screenshotbot.io/recorder | sh`
to
` curl https://screenshotbot.io/recorder.sh | sh`


on MacOS
curl https://screenshotbot.io/recorder | sh returns the 404.

**Comment by tdrhq** [comment]
Indeed it does. I'll fix it right way! Thanks for pointing it out!

**Comment by tdrhq** [comment]
Fixed. This was a typo in the docs, and this typo has been been here for ages now, sorry about that!
