### ISSUE TITLE
Reset data object with docker

### ISSUE THREAD

**Issue by iityr** [screenshotbot/screenshotbot-oss#31]
Hi @tdrhq ! 
How reset data with docker? Where is `screenshotbot/object-store`?

**Comment by tdrhq** [comment]
@iityr If you're using the default docker-compose it's this volume: https://github.com/screenshotbot/screenshotbot-oss/blob/main/docker-compose.yml#L16

You can list all your docker volumes with `docker volume ls` and delete the volume corresponding to this screenshotbot-oss (it'll depend on your root directory name, something like `dir_screenshotbot-oss`. You can delete the volume with `docker volume rm`.

Also, may I ask what issue you hit that you need to reset the volume?

**Comment by iityr** [comment]
ok, i don't need, but simple curiosity.
I have a question. I doing a little test with a test project and only a main branch.

1. Modify image and commit by other changes on code (__Snapshots__ is ignored).
2. Run recorder command
3. Refresh the screeshotbot Recent Runs element and i see the last commit, but screenshotbot don't alert the change on images?

I need, create a new branch and pass the main branch on recorder command? I don't quite understand how it works

**Comment by tdrhq** [comment]
The recorder script has a few sanity checks in place to make sure that we don't generate and send reports for runs generated by developers locally. In particular, your repository needs to be clean, and the changes you're making should be in `origin/main` (or `origin/develop`, `origin/master` etc.)

Can you open on "Debug Info" on your second run (the run with the changes), and send me what you see? (You can copy paste, and feel free to redact any information you need to)

![Screenshot from 2023-02-03 11-09-54](https://user-images.githubusercontent.com/82582/216652284-64db224c-2b7e-4591-8428-59f21df723b2.png)

**Comment by tdrhq** [comment]
But you can still manually compare runs for local runs

**Comment by iityr** [comment]
I have a main branch and develop new features on news branch. I want run snapshot and see the diference between main and feature_branch. Is is possible?

I run the command:

~/screenshotbot/recorder \
      --channel "com.tyris-software.ScreenshotBotTesting" \
      --api-key "xxxxxxxx" \
      --api-secret "xxxxxxx" \
      --directory "ScreenshotBotTestingTests/__Snapshots__" \
      --production \
      --api-hostname http://localhost:4091 \
      --main-branch main \
      --repo-url "https://github.com/iityr/ScreenshotBotTesting"

![Screenshot 2023-02-03 at 17 17 42](https://user-images.githubusercontent.com/124160050/216653227-e4c48807-aab0-46b2-858f-e029660b86f4.png)

**Comment by tdrhq** [comment]
@iityr, That's the behavior to expect. If you merge that branch to master, you'll get an email notification with the changes (and you can set this notification in Slack, Jira, etc.)

The alternative is to create a Pull Request from this branch (or even just push the branch to GitHub and configure your CI to run on all branches). You'll need to follow the steps to create a GitHub application and add that application to the Screenshotbot config etc. In that case Screenshotbot will update your Pull Request with the changes before you even merge the branch.

I do see it as an interesting possibility to get notified by email on branches. If that's something you think will be a lot more useful than PRs, we might consider building it. Right now we don't do that.

**Comment by iityr** [comment]
I've just merged the changes from feature_branch into main.
Executed the recorder command from the main branch, but I don't see the notice of those changes in the last job executed. I only see them if it is compared with the previous work.

When do new elements appear in the Reports section?

**Comment by tdrhq** [comment]
Can you show me what your `/runs` page looks like?

**Comment by tdrhq** [comment]
Roughly speaking, you'll get a report in your reports tab any time a run is "promoted". So the run on your new merged commit is not promoted, we would need to figure out why.

**Comment by iityr** [comment]
![Screenshot 2023-02-03 at 18 01 08](https://user-images.githubusercontent.com/124160050/216662791-ce3d0522-964e-4c47-9d74-5b5c7bede673.png)

**Comment by iityr** [comment]
i attach the Reports history. Only when i added and removed snapshots

![Screenshot 2023-02-03 at 18 03 07](https://user-images.githubusercontent.com/124160050/216663184-7058a2d2-62e0-4d35-a769-795a3150805a.png)

**Comment by tdrhq** [comment]
Okay, so see that the run from 5 hours ago is marked "promoted". The rest of the runs are "unpromoted". So something is happening that's preventing things from being promoted. 

Looking at your public GitHub repo, I see that 93011 is a valid commit that's pushed to origin/main. But I don't see e31d or 72a2. I see ce41291, so let's open the run corresponding to that, and hit re-run promotions in the Advanced menu? Perhaps when that run was created the change wasn't pushed to origin/main?

**Comment by iityr** [comment]
As you say, I have seen commits without pushing, all the changes are already up.

I have run the execution of ce41291 again and I get the following log:

 ```
--BEGIN-LOGS--
INFO Beginning promotion: #<SB-SYS:FD-STREAM for "file /data/promotion-logs/63/dc/fb619da6a00f7d97e06f" {10084C2883}>
INFO Running promoter: #<SCREENSHOTBOT/API/PROMOTE:DEFAULT-PROMOTER {10084C2BC3}> on #<SCREENSHOTBOT/MODEL/RECORDER-RUN:RECORDER-RUN ID: 34>
INFO Delegating to promoter #<SCREENSHOTBOT/API/PROMOTE:MASTER-PROMOTER {10084C2C83}>
INFO Running promoter: #<SCREENSHOTBOT/API/PROMOTE:MASTER-PROMOTER {10084C2C83}> on #<SCREENSHOTBOT/MODEL/RECORDER-RUN:RECORDER-RUN ID: 34>
INFO Begin image verifications for #<RECORDER-RUN ID: 34>
INFO Inside promotion logic
INFO Branch on run: main
INFO previous run: #<SCREENSHOTBOT/MODEL/RECORDER-RUN:RECORDER-RUN ID: 24>
INFO Attempting switch: 9301153456f732ac06fe4ba2cc739cca2080d601 -> ce41291532193703c19884516639576ac84b1fd8
INFO According to run master has branch-hash 9301153456f732ac06fe4ba2cc739cca2080d601
INFO Checking ancestry (channel: 7): 9301153456f732ac06fe4ba2cc739cca2080d601 9301153456f732ac06fe4ba2cc739cca2080d601
INFO Checking ancestry (channel: 7): ce41291532193703c19884516639576ac84b1fd8 9301153456f732ac06fe4ba2cc739cca2080d601
ERROR The commit ce41291532193703c19884516639576ac84b1fd8 is not in branch main
INFO Delegating to promoter #<SCREENSHOTBOT/GITLAB/MERGE-REQUEST-PROMOTER:MERGE-REQUEST-PROMOTER {10084C2D13}>
INFO Running promoter: #<SCREENSHOTBOT/GITLAB/MERGE-REQUEST-PROMOTER:MERGE-REQUEST-PROMOTER {10084C2D13}> on #<SCREENSHOTBOT/MODEL/RECORDER-RUN:RECORDER-RUN ID: 34>
INFO End promotion
INFO Beginning promotion: #<SB-SYS:FD-STREAM for "file /data/promotion-logs/63/dc/fb619da6a00f7d97e06f" {10085A2783}>
INFO Running promoter: #<SCREENSHOTBOT/API/PROMOTE:DEFAULT-PROMOTER {10085A2AC3}> on #<SCREENSHOTBOT/MODEL/RECORDER-RUN:RECORDER-RUN ID: 34>
INFO Delegating to promoter #<SCREENSHOTBOT/API/PROMOTE:MASTER-PROMOTER {10085A2B83}>
INFO Running promoter: #<SCREENSHOTBOT/API/PROMOTE:MASTER-PROMOTER {10085A2B83}> on #<SCREENSHOTBOT/MODEL/RECORDER-RUN:RECORDER-RUN ID: 34>
INFO Begin image verifications for #<RECORDER-RUN ID: 34>
INFO Inside promotion logic
INFO Branch on run: main
INFO previous run: #<SCREENSHOTBOT/MODEL/RECORDER-RUN:RECORDER-RUN ID: 24>
INFO Attempting switch: 9301153456f732ac06fe4ba2cc739cca2080d601 -> ce41291532193703c19884516639576ac84b1fd8
INFO According to run master has branch-hash 9301153456f732ac06fe4ba2cc739cca2080d601
INFO Checking ancestry (channel: 7): 9301153456f732ac06fe4ba2cc739cca2080d601 9301153456f732ac06fe4ba2cc739cca2080d601
INFO Checking ancestry (channel: 7): ce41291532193703c19884516639576ac84b1fd8 9301153456f732ac06fe4ba2cc739cca2080d601
ERROR The commit ce41291532193703c19884516639576ac84b1fd8 is not in branch main
INFO Delegating to promoter #<SCREENSHOTBOT/GITLAB/MERGE-REQUEST-PROMOTER:MERGE-REQUEST-PROMOTER {10085A2C13}>
INFO Running promoter: #<SCREENSHOTBOT/GITLAB/MERGE-REQUEST-PROMOTER:MERGE-REQUEST-PROMOTER {10085A2C13}> on #<SCREENSHOTBOT/MODEL/RECORDER-RUN:RECORDER-RUN ID: 34>
INFO End promotion
INFO Beginning promotion: #<SB-SYS:FD-STREAM for "file /data/promotion-logs/63/dc/fb619da6a00f7d97e06f" {10084E24F3}>
INFO Running promoter: #<SCREENSHOTBOT/API/PROMOTE:DEFAULT-PROMOTER {10084E2833}> on #<SCREENSHOTBOT/MODEL/RECORDER-RUN:RECORDER-RUN ID: 34>
INFO Delegating to promoter #<SCREENSHOTBOT/API/PROMOTE:MASTER-PROMOTER {10084E28F3}>
INFO Running promoter: #<SCREENSHOTBOT/API/PROMOTE:MASTER-PROMOTER {10084E28F3}> on #<SCREENSHOTBOT/MODEL/RECORDER-RUN:RECORDER-RUN ID: 34>
INFO Begin image verifications for #<RECORDER-RUN ID: 34>
INFO Inside promotion logic
INFO Branch on run: main
INFO previous run: #<SCREENSHOTBOT/MODEL/RECORDER-RUN:RECORDER-RUN ID: 24>
INFO Attempting switch: 9301153456f732ac06fe4ba2cc739cca2080d601 -> ce41291532193703c19884516639576ac84b1fd8
INFO According to run master has branch-hash 9301153456f732ac06fe4ba2cc739cca2080d601
INFO Checking ancestry (channel: 7): 9301153456f732ac06fe4ba2cc739cca2080d601 9301153456f732ac06fe4ba2cc739cca2080d601
INFO Checking ancestry (channel: 7): ce41291532193703c19884516639576ac84b1fd8 9301153456f732ac06fe4ba2cc739cca2080d601
ERROR The commit ce41291532193703c19884516639576ac84b1fd8 is not in branch main
INFO Delegating to promoter #<SCREENSHOTBOT/GITLAB/MERGE-REQUEST-PROMOTER:MERGE-REQUEST-PROMOTER {10084E2983}>
INFO Running promoter: #<SCREENSHOTBOT/GITLAB/MERGE-REQUEST-PROMOTER:MERGE-REQUEST-PROMOTER {10084E2983}> on #<SCREENSHOTBOT/MODEL/RECORDER-RUN:RECORDER-RUN ID: 34>
INFO End promotion
INFO Beginning promotion: #<SB-SYS:FD-STREAM for "file /data/promotion-logs/63/dc/fb619da6a00f7d97e06f" {10083C2193}>
INFO Running promoter: #<SCREENSHOTBOT/API/PROMOTE:DEFAULT-PROMOTER {10083C24D3}> on #<SCREENSHOTBOT/MODEL/RECORDER-RUN:RECORDER-RUN ID: 34>
INFO Delegating to promoter #<SCREENSHOTBOT/API/PROMOTE:MASTER-PROMOTER {10083C2593}>
INFO Running promoter: #<SCREENSHOTBOT/API/PROMOTE:MASTER-PROMOTER {10083C2593}> on #<SCREENSHOTBOT/MODEL/RECORDER-RUN:RECORDER-RUN ID: 34>
INFO Begin image verifications for #<RECORDER-RUN ID: 34>
INFO Inside promotion logic
INFO Branch on run: main
INFO previous run: #<SCREENSHOTBOT/MODEL/RECORDER-RUN:RECORDER-RUN ID: 24>
INFO Attempting switch: 9301153456f732ac06fe4ba2cc739cca2080d601 -> ce41291532193703c19884516639576ac84b1fd8
INFO According to run master has branch-hash 9301153456f732ac06fe4ba2cc739cca2080d601
INFO Checking ancestry (channel: 7): 9301153456f732ac06fe4ba2cc739cca2080d601 9301153456f732ac06fe4ba2cc739cca2080d601
INFO Checking ancestry (channel: 7): ce41291532193703c19884516639576ac84b1fd8 9301153456f732ac06fe4ba2cc739cca2080d601
ERROR The commit ce41291532193703c19884516639576ac84b1fd8 is not in branch main
INFO Delegating to promoter #<SCREENSHOTBOT/GITLAB/MERGE-REQUEST-PROMOTER:MERGE-REQUEST-PROMOTER {10083C2623}>
INFO Running promoter: #<SCREENSHOTBOT/GITLAB/MERGE-REQUEST-PROMOTER:MERGE-REQUEST-PROMOTER {10083C2623}> on #<SCREENSHOTBOT/MODEL/RECORDER-RUN:RECORDER-RUN ID: 34>
INFO End promotion

  --END-LOGS--
```

The error indicates that the commit ce41291532193703c19884516639576ac84b1fd8 is not in the main branch. But yes, this:

https://github.com/iityr/ScreenshotBotTesting/commit/ce41291532193703c19884516639576ac84b1fd8

**Comment by tdrhq** [comment]
@iityr Okay, got it. So roughly speaking here's how this works (there may be some details that I'm missing):

When you create a run with the CLI, we upload the Git commit graph, only the git hashes and for each git hash, we keep track of the parent commit hashes. So from this point onwards, we use this graph as the source of truth to do branch checks etc.

Importantly, this graph does not have the mapping of branch names to commits (e.g. that `main` is ce4129 etc.) For each run, you specify the main branch with `--main-branch`, and the CLI tool figures out what the commit of the main branch is when that run happened. This is the "Commit on branch" in the "Debug Info" (I should rename that). Actually, to be more precise, this looks at `origin/main`.

So even if you re-run the promotion, it will still use the state with respect to when you first created the run. And at the time of creating this run, this commit was not in origin/main.

So the way to fix this is to just make sure you're running the CLI on a clean repo, on a commit that's already pushed to origin/main. As long as 9301153 is an ancestor of the new commit, the promotion will go through.

**Comment by iityr** [comment]
ok, i think i got it, i created the feat3 branch, pushed it to the repository and merged changes into main. Then I have executed and the changes appear.

I need to verify how I work with pull requests, I'll tell you when I try.

thank you very much!

**Comment by tdrhq** [comment]
Closing out issue for now, let me know if you still have questions!
