### ISSUE TITLE
Usage within docker images

### ISSUE THREAD

**Issue by petrisorciprian-vitals** [screenshotbot/screenshotbot-oss#33]
Hello, I was attempting to install this via the official script, as follows:
```
    curl https://screenshotbot.io/recorder.sh | sh
```

However, kept running into the following error instead:
![image](https://github.com/screenshotbot/screenshotbot-oss/assets/136788902/286d4705-f90e-46ce-bbf7-cb8384207300)

Initially I thought something was wrong with the archive it unzipped not containing the installer.sh, but upon further debugging it seems that the shebang in the installer.sh script is to blame.
https://github.com/screenshotbot/screenshotbot-oss/blob/fbe83e47bb482a3066f3db7cf6d54b24a3b13af3/src/screenshotbot/sdk/installer.sh#L1

There are many docker images that do not come with ```bash``` preinstalled; either a check to ensure bash is available in the installer or updating the installer.sh to be ```sh``` compatible would greatly help.

**Comment by tdrhq** [comment]
Oh great catch! This code is outside of any crash logging we do, so I have to make this change very carefully, let me see if I can get it done by EOD
