### ISSUE TITLE
No web-interface after launching screenshotbot with Docker

### ISSUE THREAD

**Issue by gopito** [screenshotbot/screenshotbot-oss#38]
I launched screenshotbot with Docker command:
`$ docker-compose up --build`
I have issues with "**openjdk-11-jre-headless**" package. I changed it to "**openjdk-17-jre-headless**" and managed to build docker image. But when I went to **localhost:4091** I only saw:
<img width="395" alt="image" src="https://github.com/screenshotbot/screenshotbot-oss/assets/894735/999f0c70-2056-40bf-8fca-cc7e21ac0439">

Then I changed docker file to install java liberica instead:
`RUN curl -s "https://get.sdkman.io?rcupdate=false" | bash && source "/root/.sdkman/bin/sdkman-init.sh" && sdk install java 11.0.22-librca`

I have the same result, no interface is shown:
<img width="395" alt="image" src="https://github.com/screenshotbot/screenshotbot-oss/assets/894735/999f0c70-2056-40bf-8fca-cc7e21ac0439">

Do I need to edit **config.lisp** file to get web-interface or maybe I need an earlier **debian** base image in docker file?

I am launching it in MacOS in [colima](https://github.com/abiosoft/colima). I've tried with Rosetta emulation too.

**Comment by tdrhq** [comment]
@gopito Fixed, please git pull and try again!
